services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html

    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
